# Generated by Django 4.2.30 on 2026-09-19 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('MONTANA', 'Montaña'), ('RUTA', 'Ruta'), ('URBANA', 'Urbana'), ('ELECTRICA', 'Eléctrica'), ('INFANTIL', 'Infantil')], max_length=20)),
                ('aro', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(80)])),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bicicleta',
                'verbose_name_plural': 'Bicicletas',
                'ordering': ['-id'],
            },
        ),
    ]
