# Generated by Django 4.2.30 on 2026-09-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0002_alter_bicicleta_aro_alter_bicicleta_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='marca',
            field=models.CharField(choices=[('Alta Gama e Internacionales', [('TREK', 'Trek'), ('SPECIALIZED', 'Specialized'), ('GIANT', 'Giant'), ('SCOTT', 'Scott'), ('CANNONDALE', 'Cannondale'), ('ORBEA', 'Orbea'), ('PINARELLO', 'Pinarello'), ('BIANCHI', 'Bianchi'), ('CERVELO', 'Cervélo'), ('BMC', 'BMC Switzerland'), ('SANTA_CRuz', 'Santa Cruz'), ('YETI', 'Yeti Cycles'), ('GT', 'GT Bicycles'), ('MERIDA', 'Merida'), ('KTM', 'KTM Bikes'), ('CUBE', 'Cube Bikes'), ('FOCUS', 'Focus Bikes'), ('WILIER', 'Wilier Triestina'), ('COLNAGO', 'Colnago'), ('DE_ROSA', 'De Rosa'), ('RIDLEY', 'Ridley'), ('LOOK', 'Look Cycle'), ('TIME', 'Time Sport'), ('FACTOR', 'Factor Bikes'), ('ARGON_18', 'Argon 18'), ('LAPIERRE', 'Lapierre'), ('COMMENCAL', 'Commencal'), ('TRANSITION', 'Transition Bikes'), ('NORCO', 'Norco'), ('KONA', 'Kona'), ('ROCKY_MOUNTAIN', 'Rocky Mountain'), ('INTENSE', 'Intense Cycles'), ('EVIL', 'Evil Bikes'), ('IBIS', 'Ibis Cycles'), ('PIVOT', 'Pivot Cycles'), ('MACEK', 'Macek'), ('BANSHEE', 'Banshee Bikes'), ('NS_BIKES', 'NS Bikes'), ('DARTMOOR', 'Dartmoor'), ('STUMPJUMPER', 'Stumpjumper')]), ('Masivas y Populares en Chile', [('OXFORD', 'Oxford'), ('UPLAND', 'Upland'), ('LEADER', 'Leader'), ('PRO_MAX', 'Pro Max'), ('AVANT', 'Avant'), ('ROBUSTA', 'Robusta'), ('KRONOS', 'Kronos'), ('WINDSOR', 'Windsor'), ('BENOTTO', 'Benotto'), ('MONGOOSE', 'Mongoose'), ('SCHWINN', 'Schwinn'), ('HARO', 'Haro Bikes'), ('DIAMONDBACK', 'Diamondback'), ('RALEIGH', 'Raleigh'), ('HASA', 'Hasa'), ('TRINX', 'Trinx'), ('JAVA', 'Java Bikes'), ('SAVA', 'Sava'), ('TWITTER', 'Twitter Bikes'), ('AUDACIOUS', 'Audacious'), ('MOOSE', 'Moose'), ('CANNON', 'Cannon'), ('STARK', 'Stark'), ('MOSSO', 'Mosso'), ('SHOGUN', 'Shogun'), ('KENSLER', 'Kensler'), ('ECLIPSE', 'Eclipse'), ('FROST', 'Frost')]), ('Urbanas, Plegables y Eléctricas', [('DECATHLON', "Decathlon / B'Twin"), ('ELECTRA', 'Electra'), ('BROOKLYN', 'Brooklyn Bicycle Co.'), ('STRIDA', 'Strida'), ('BROMPTON', 'Brompton'), ('TERN', 'Tern'), ('DAHON', 'Dahon'), ('GAZELLE', 'Gazelle'), ('RAD_POWER', 'Rad Power Bikes'), ('HAIBIKE', 'Haibike'), ('SPECIALIZED_E', 'Specialized Turbo'), ('BULLS', 'Bulls Bikes')]), ('BMX y Freestyle', [('PRIMO', 'Primo'), ('SUBROSA', 'Subrosa'), ('WETHEPEOPLE', 'WeThePeople'), ('DIAMOND', 'Diamond'), ('BSD', 'BSD'), ('ODYSSEY', 'Odyssey'), ('CULT', 'Cult Crew'), ('STOLEN', 'Stolen Bikes'), ('SE_BIKES', 'SE Bikes'), ('FIT_BIKE_CO', 'Fit Bike Co.')]), ('Otras', [('OTRA', 'Otra / Genérica')])], max_length=40),
        ),
    ]
