# Generated by Django 4.2.30 on 2026-09-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0003_alter_bicicleta_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='categoria',
            field=models.CharField(blank=True, default='DEPORTIVA', max_length=30),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='es_destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='es_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='especificaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('RESERVADO', 'Reservado')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='marca',
            field=models.CharField(choices=[('Alta Gama e Internacionales', [('TREK', 'Trek'), ('SPECIALIZED', 'Specialized'), ('GIANT', 'Giant'), ('SCOTT', 'Scott'), ('CANNONDALE', 'Cannondale'), ('ORBEA', 'Orbea'), ('PINARELLO', 'Pinarello'), ('BIANCHI', 'Bianchi'), ('CERVELO', 'Cervélo'), ('BMC', 'BMC Switzerland'), ('SANTA_CRUZ', 'Santa Cruz'), ('YETI', 'Yeti Cycles'), ('GT', 'GT Bicycles'), ('MERIDA', 'Merida'), ('KTM', 'KTM Bikes'), ('CUBE', 'Cube Bikes'), ('FOCUS', 'Focus Bikes'), ('WILIER', 'Wilier Triestina'), ('COLNAGO', 'Colnago'), ('DE_ROSA', 'De Rosa'), ('RIDLEY', 'Ridley'), ('LOOK', 'Look Cycle'), ('TIME', 'Time Sport'), ('FACTOR', 'Factor Bikes'), ('ARGON_18', 'Argon 18'), ('LAPIERRE', 'Lapierre'), ('COMMENCAL', 'Commencal'), ('TRANSITION', 'Transition Bikes'), ('NORCO', 'Norco'), ('KONA', 'Kona'), ('ROCKY_MOUNTAIN', 'Rocky Mountain'), ('INTENSE', 'Intense Cycles'), ('EVIL', 'Evil Bikes'), ('IBIS', 'Ibis Cycles'), ('PIVOT', 'Pivot Cycles'), ('MACEK', 'Macek'), ('BANSHEE', 'Banshee Bikes'), ('NS_BIKES', 'NS Bikes'), ('DARTMOOR', 'Dartmoor'), ('STUMPJUMPER', 'Stumpjumper')]), ('Masivas y Populares en Chile', [('OXFORD', 'Oxford'), ('UPLAND', 'Upland'), ('LEADER', 'Leader'), ('PRO_MAX', 'Pro Max'), ('AVANT', 'Avant'), ('ROBUSTA', 'Robusta'), ('KRONOS', 'Kronos'), ('WINDSOR', 'Windsor'), ('BENOTTO', 'Benotto'), ('MONGOOSE', 'Mongoose'), ('SCHWINN', 'Schwinn'), ('HARO', 'Haro Bikes'), ('DIAMONDBACK', 'Diamondback'), ('RALEIGH', 'Raleigh'), ('HASA', 'Hasa'), ('TRINX', 'Trinx'), ('JAVA', 'Java Bikes'), ('SAVA', 'Sava'), ('TWITTER', 'Twitter Bikes'), ('AUDACIOUS', 'Audacious'), ('MOOSE', 'Moose'), ('CANNON', 'Cannon'), ('STARK', 'Stark'), ('MOSSO', 'Mosso'), ('SHOGUN', 'Shogun'), ('KENSLER', 'Kensler'), ('ECLIPSE', 'Eclipse'), ('FROST', 'Frost')]), ('Urbanas, Plegables y Eléctricas', [('DECATHLON', "Decathlon / B'Twin"), ('ELECTRA', 'Electra'), ('BROOKLYN', 'Brooklyn Bicycle Co.'), ('STRIDA', 'Strida'), ('BROMPTON', 'Brompton'), ('TERN', 'Tern'), ('DAHON', 'Dahon'), ('GAZELLE', 'Gazelle'), ('RAD_POWER', 'Rad Power Bikes'), ('HAIBIKE', 'Haibike'), ('SPECIALIZED_E', 'Specialized Turbo'), ('BULLS', 'Bulls Bikes')]), ('BMX y Freestyle', [('PRIMO', 'Primo'), ('SUBROSA', 'Subrosa'), ('WETHEPEOPLE', 'WeThePeople'), ('DIAMOND', 'Diamond'), ('BSD', 'BSD'), ('ODYSSEY', 'Odyssey'), ('CULT', 'Cult Crew'), ('STOLEN', 'Stolen Bikes'), ('SE_BIKES', 'SE Bikes'), ('FIT_BIKE_CO', 'Fit Bike Co.')]), ('Otras', [('OTRA', 'Otra / Genérica')])], max_length=40),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta de Crédito/Débito')], default='EFECTIVO', max_length=30)),
                ('impuesto', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.bicicleta')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bicicletas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.bicicleta')),
            ],
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='categoria_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bicicletas.categoria'),
        ),
    ]
