# Generated by Django 4.2.30 on 2026-09-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0004_categoria_cliente_bicicleta_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
