# Generated by Django 4.2.30 on 2026-09-21 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0005_categoria_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('segmento', models.CharField(default='MASIVA', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='modelo',
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='bicicletas.marca')),
            ],
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='modelo_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bicicletas.modelo'),
        ),
    ]
