# Generated by Django 4.2.30 on 2026-09-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0008_modelo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemventa',
            name='bicicleta',
        ),
        migrations.RemoveField(
            model_name='itemventa',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ItemVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
